/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    Bottom1: typeof import('./src/components/nav/Bottom1.vue')['default']
    Bread: typeof import('./src/components/coms/Bread.vue')['default']
    Button: typeof import('./src/components/coms/Button.vue')['default']
    Expan: typeof import('./src/components/coms/Expan.vue')['default']
    Fbutton: typeof import('./src/components/coms/Fbutton.vue')['default']
    Footers: typeof import('./src/components/coms/Footers.vue')['default']
    HelloWorld: typeof import('./src/components/coms/HelloWorld.vue')['default']
    Home: typeof import('./src/components/coms/Home.vue')['default']
    Layout3: typeof import('./src/components/layout/layout3.vue')['default']
    LayoutOne: typeof import('./src/components/layout/LayoutOne.vue')['default']
    LayoutTwo: typeof import('./src/components/layout/LayoutTwo.vue')['default']
    Nav1: typeof import('./src/components/nav/Nav1.vue')['default']
    Nav2: typeof import('./src/components/nav/Nav2.vue')['default']
    Nav3: typeof import('./src/components/nav/Nav3.vue')['default']
    Nav4: typeof import('./src/components/nav/Nav4.vue')['default']
    Nav5: typeof import('./src/components/nav/Nav5.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tooltip: typeof import('./src/components/coms/Tooltip.vue')['default']
    Tooltips: typeof import('./src/components/coms/Tooltips.vue')['default']
  }
}
